### ISSUE TITLE
Error: this component requires your app theme to be Theme.AppCompat

### ISSUE THREAD

**Issue by pablo03v** [rafi0101/Android-Room-Database-Backup#33]
[crash.json](https://github.com/rafi0101/Android-Room-Database-Backup/files/14806183/crash.json)

https://github.com/pabloscloud/Overload/tree/28-new-backup-implementation

Backing up works fine but importing throws an error:

> ACRA caught a IllegalArgumentException for cloud.pablos.overload.debug
                                                                                                    java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.AppCompat (or a descendant).
                                                                                                    	at com.google.android.material.internal.ThemeEnforcement.checkTheme(ThemeEnforcement.java:247)
                                                                                                    	at com.google.android.material.internal.ThemeEnforcement.checkAppCompatTheme(ThemeEnforcement.java:212)
                                                                                                    	at com.google.android.material.internal.ThemeEnforcement.checkCompatibleTheme(ThemeEnforcement.java:147)
                                                                                                    	at com.google.android.material.internal.ThemeEnforcement.obtainStyledAttributes(ThemeEnforcement.java:76)
                                                                                                    	at com.google.android.material.dialog.MaterialDialogs.getDialogBackgroundInsets(MaterialDialogs.java:60)
                                                                                                    	at com.google.android.material.dialog.MaterialAlertDialogBuilder.<init>(MaterialAlertDialogBuilder.java:123)
                                                                                                    	at com.google.android.material.dialog.MaterialAlertDialogBuilder.<init>(MaterialAlertDialogBuilder.java:109)
                                                                                                    	at de.raphaelebner.roomdatabasebackup.core.RoomBackup.restore(RoomBackup.kt:551)
                                                                                                    	at cloud.pablos.overload.ui.tabs.configurations.ConfigurationsTabKt.import(ConfigurationsTab.kt:448)

**Comment by pablo03v** [comment]
got this fixed on my end.. nvm sry
